services:
  backend:
    build:
      context: ./backend
    container_name: backend-api
    command: npm run dev
    working_dir: /app
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_NAME=profile_db
      - DB_PORT=3306
      - JWT_SECRET=secret
    depends_on:
      - db

  frontend:
    image: node:20-alpine
    container_name: frontend-app
    command: sh -c "npm install && npm run dev -- --host"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:5173"
    depends_on:
      - backend
      
  db:
    container_name: profile_kirvano_db
    image: mysql:8.0.32
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge