# docker-compose.yml
services:
  profile-app:
    build: .
    user: node
    container_name: profile-api
    tty: true
    stdin_open: true
    command: npm run dev
    restart: always
    working_dir: /app
    volumes:
      - ./src/:/app/src
      - ./tests/:/app/tests
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: profile_db
      DB_PORT: 3306
      JWT_SECRET: secret
  db:
    container_name: profile_db
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password